export const propsDataGrid = {
    toolbarColumns: 'Columnas',
    toolbarColumnsLabel: 'Seleccionar columnas',
    filterPanelOperator: 'Operación',
    filterPanelInputLabel: 'Valor',
    filterPanelInputPlaceholder: 'Valor para filtrar',
    columnMenuSortAsc: 'Ascendente',
    columnMenuSortDesc: 'Descendente',
    columnMenuFilter: 'Filtro',
    columnMenuUnsort: 'Desordenar',
    toolbarFiltersTooltipHide: 'Ocultar filtros',
    toolbarFiltersTooltipShow: 'Mostrar filtros',
    columnMenuManageColumns: 'Administrar columnas',
    columnsManagementShowHideAllText: 'Esconder/Mostrar Todo',
    // Total row amount footer text
    footerTotalRows: 'Filas totales',
    filterPanelAddFilter: 'Agregar filtro',
    filterPanelRemoveAll: 'Eliminar todos',
    filterPanelDeleteIconLabel: 'Eliminar',
    filterPanelLogicOperator: 'Operador lógico',
    filterPanelOperator: 'Operador',
    filterPanelOperatorAnd: 'Y',
    filterPanelOperatorOr: 'O',
    filterPanelColumns: 'Columnas',
    filterPanelInputLabel: 'Valor',

    // Total visible row amount footer text
    footerTotalVisibleRows: (visibleCount, totalCount) =>
        `${visibleCount.toLocaleString()} of ${totalCount.toLocaleString()}`,

    // Checkbox selection text
    checkboxSelectionHeaderName: 'Checkbox selection',
    checkboxSelectionSelectAllRows: 'Seleccionar todas las filas',
    checkboxSelectionUnselectAllRows: 'Quitar selección total',
    checkboxSelectionSelectRow: 'Seleccionar fila',
    checkboxSelectionUnselectRow: 'Quitar selección',
    noRowsLabel: 'Sin filas',
    noResultsOverlayLabel: 'No se encontraron resultados',
    footerRowSelected: (count) =>
        count !== 1
          ? `${count.toLocaleString()} filas seleccionadas`
          : `${count.toLocaleString()} fila seleccionada`,
    booleanCellTrueLabel: 'si',
    booleanCellFalseLabel: 'no',
    actionsCellMore: 'más',
    headerFilterOperatorContains: 'Contiene',
    headerFilterOperatorEquals: 'Es igual a',
    headerFilterOperatorStartsWith: 'Comienza con',
    headerFilterOperatorEndsWith: 'Termina con',
    headerFilterOperatorIs: 'Es',
    headerFilterOperatorNot: 'No es',
    headerFilterOperatorAfter: 'Es después de',
    headerFilterOperatorOnOrAfter: 'Es en o después de',
    headerFilterOperatorBefore: 'Es antes de',
    headerFilterOperatorOnOrBefore: 'Es en o antes de',
    headerFilterOperatorIsEmpty: 'Está vacío',
    headerFilterOperatorIsNotEmpty: 'No está vacío',
    headerFilterOperatorIsAnyOf: 'Es alguno de',
    'headerFilterOperator=': 'Es igual a',
    'headerFilterOperator!=': 'No es igual a',
    'headerFilterOperator>': 'Mayor que',
    'headerFilterOperator>=': 'Mayor o igual que',
    'headerFilterOperator<': 'Menor que',
    'headerFilterOperator<=': 'Menor o igual que',
    filterValueAny: 'ninguno',
    filterValueTrue: 'verdadero',
    filterValueFalse: 'falso',

    columnMenuHideColumn: 'Ocultar columna',

    // Texto de los operadores de filtro
    filterOperatorContains: 'contiene',
    filterOperatorEquals: 'es igual a',
    filterOperatorStartsWith: 'comienza con',
    filterOperatorEndsWith: 'termina con',
    filterOperatorIs: 'es',
    filterOperatorNot: 'no es',
    filterOperatorAfter: 'es después de',
    filterOperatorOnOrAfter: 'es en o después de',
    filterOperatorBefore: 'es antes de',
    filterOperatorOnOrBefore: 'es en o antes de',
    filterOperatorIsEmpty: 'está vacío',
    filterOperatorIsNotEmpty: 'no está vacío',
    filterOperatorIsAnyOf: 'es alguno de',
    'filterOperator=': '=',
    'filterOperator!=': '!=',
    'filterOperator>': '>',
    'filterOperator>=': '>=',
    'filterOperator<': '<',
    'filterOperator<=': '<=',


    toolbarFilters: 'Filtros',
    toolbarFiltersLabel: 'Mostrar filtros',
    toolbarFiltersTooltipHide: 'Ocultar filtros',
    toolbarFiltersTooltipShow: 'Mostrar filtros',
    toolbarFiltersTooltipActive: (count) =>
    count !== 1 ? `${count} filtros activos` : `${count} filtro activo`,
}